- name: "install apt-get packages"
  apt:
    name: [ "dnsmasq", "hostapd", "screen", "python3-pip", "python3-setuptools", "python3-wheel", "mosquitto", "nodejs", "haveged", "git", "curl", "build-essential", "python-pip", "python3-pip", "python-setuptools", "python3-setuptools", "python-wheel", "python3-wheel", "python-dev", "python3-dev", "mosquitto", "haveged", "net-tools", "libssl-dev" ]
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: "install pip packages"
  pip:
    name:       [ "paho-mqtt", "httplib2", "netifaces", "pyaes", "tornado", "pycrypto", "git+https://github.com/M4dmartig4n/sslpsk.git" ]
    executable: pip3

- name: unarchive node
  unarchive:
    src: node-v13.0.1-linux-armv7l.tar.gz
    dest: /usr/local/

- name: unarchive SonOTA.zip
  unarchive:
    src: SonOTA.zip
    dest: /home/pi
  become_user: pi
  become: yes

- name: Copy wifi script
  copy:
    src:  wifi.sh
    dest: /home/pi/wifi.sh
    mode: '750'
  become_user: pi
  become: yes

- name: scan wifi
  command: '/home/pi/wifi.sh {{ wifi }} {{ password }} /home/pi/tasmota.log'
  become_user: pi
  become: yes
