- name: "install apt-get packages"
  apt:
    name: [ "dnsmasq", "hostapd", "screen", "python3-pip", "python3-setuptools", "python3-wheel", "mosquitto", "nodejs", "haveged", "git" ]
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: "install pip packages"
  pip:
    name:       [ "paho-mqtt", "pyaes", "tornado" ]
    executable: pip-3.3

- name: tuya-convert
  unarchive:
    src: node-v13.0.1-linux-armv7l.tar.gz
    dest: ~/tuya-convert

- name: my ip
  set_fact:
    ip: hostvars[inventory_hostname]['ansible_env'].SSH_CONNECTION.split(' ')[2]

- name: start
  command: "python3 sonota.py --serving-host {{ ip }} --wifi-ssid revenberg-24G --wifi-password {{ ?? }}"
  args:
    chdir: ~
